<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "logs".
 *
 * @property int $idLogs
 * @property int $User_id
 * @property string $description
 * @property string $transacao
 *
 * @property Userprofile $user
 */
class Logs extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'logs';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['User_id'], 'integer'],
            [['description'], 'string', 'max' => 50],
            [['transacao'], 'string', 'max' => 20],
            [['User_id'], 'exist', 'skipOnError' => true, 'targetClass' => Userprofile::className(), 'targetAttribute' => ['User_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'idLogs' => 'Id Logs',
            'User_id' => 'User ID',
            'description' => 'Description',
            'transacao' => 'Transacao',
        ];
    }
    public function beforeSave($insert)
    {
        $userid = Yii::$app->user->getId();
        $profileid = Userprofile::findOne(['user_id' => $userid])->id;
        $this->User_id = $profileid;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Userprofile::className(), ['id' => 'User_id']);
    }
}
