# Generated by Django 2.2 on 2019-04-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number (order)'),
        ),
    ]
